#include "Source\Pseudo.h"

CLASE( LLAMADA(Testerino))
ACCESO_PUBLICO
	CREAR_VARIABLE(CON_TIPO DE ENTERO, LLAMADA(test))
	CREAR_VARIABLE(CON_TIPO DE DECIMAL, LLAMADA(test2))
	DECLARAR_FUNCION(LLAMADA(test3), QUE_REGRESA_UN(ENTERO), Y_RECIBE(UN ENTERO POR_REFERENCIA LLAMADO(test) ADEMAS_DE UN ENTERO LLAMADO(test2)))
FIN_DE_LA_CLASE

FUNCION_DE_CLASE(LLAMADA(test3), QUE_REGRESA_UN(ENTERO), Y_RECIBE(UN ENTERO POR_REFERENCIA LLAMADO(test)
	ADEMAS_DE UN ENTERO LLAMADO(test2)), Y_LE_PERTENECE_A_LA_CLASE(Testerino))
	ASIGNAR_A(test, test2 MAS test)
	REGRESAR_VALOR(test)
FIN_DE_LA_FUNCION

ESTRUCTURA( LLAMADA(Testerono))
	CREAR_VARIABLE(CON_TIPO DE ENTERO, LLAMADA(test))
	CREAR_VARIABLE(CON_TIPO DE DECIMAL, LLAMADA(test2))
FIN_DE_LA_ESTRUCTURA( LLAMADA(Testerono))

CLASE( LLAMADA(Testeman), QUE HEREDA_DE LA CLASE_PUBLICA(Testerino))
ACCESO_PUBLICO
	CREAR_VARIABLE(CON_TIPO DE Testerono, LLAMADA(test1))
	CREAR_VARIABLE(CON_TIPO DE APUNTADOR_DE(ENTERO), LLAMADA(testApuntador))
	DECLARAR_CONSTRUCTOR(LLAMADO(Testeman))
	DECLARAR_DESTRUCTOR(LLAMADO(Testeman))
FIN_DE_LA_CLASE

IMPLEMENTAR_CONSTRUCTOR(LLAMADO(Testeman))
	LLENAR_ESTRUCTURA(LLAMADA(test1), 1, 22.2f)
	ALOCAR_MEMORIA(EN testApuntador, COMO_UN ENTERO, CON_EL_VALOR_DE(22))
	DESTRUIR_VARIABLE(LLAMADA(testApuntador))
FIN_DEL_CONSTRUCTOR

IMPLEMENTAR_DESTRUCTOR(Testeman)

FIN_DEL_DESTRUCTOR

PROGRAMA
	SI 2 ES_IGUAL_A 22 O 3 ES_MENOR_QUE 5 ENTONCES
		IMPRIMIR 22 LUEGO TERMINAR_LA_LINEA
	DESPUES TERMINAR_LA_COMPROBACION
	LUEGO
	CREAR_ARREGLO(CON_TIPO DE ENTERO, LLAMADO(elArreglo))
	CREAR_VARIABLE(CON_TIPO DE ENTERO, LLAMADA(iterador))
	MIENTRAS iterador SEA_MENOR_QUE 50 HAZ
		AGREGAR_AL_ARREGLO(elArreglo, UN NUMERO_ALEATORIO_EN_RANGO(0,1000))
	FIN_DE_LA_ITERACION
	CREAR_VARIABLE(CON_TIPO DE ENTERO, LLAMADA(elMaximo))
	ASIGNAR_A(elMaximo, EL_VALOR_DE(0))
	PARA CADA(numero) EN elArreglo HAZ
		SI EL numero ES_MAYOR_QUE elMaximo ENTONCES
			ASIGNAR_A(elMaximo, EL_VALOR_DE(EL numero))
		DESPUES TERMINAR_LA_COMPROBACION
	FIN_DE_LA_ITERACION
	IMPRIMIR elMaximo LUEGO TERMINAR_LA_LINEA
	DESPUES PAUSAR_EL_PROGRAMA
FIN_DEL_PROGRAMA